version: "3.7"

services:
  # Client side React or Vue
  client:
    # command: start
    # since we are wanting to run our
    # containers using a file other than
    # that the default Dockerfile.
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      # we specify a context
      context: ./client
      # and the location of the file
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.dev
    # what port we want to make available
    ports:
      - "3000:3000"
    # here we bind our volumes
    volumes:
      # don't try to map a folder against
      # our node modules
      - /home/node/app/node_modules
      # map the current dir outside the
      # container to the app folder
      # inside the container
      - ./client:/home/node/app